# Generated by Django 3.2.20 on 2023-08-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230803_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='activity',
        ),
    ]
